theme: jekyll-dash
title: devnomadic
description: "<span style='color:#e74c3c'>&quot;</span><span style='color:#3498db'>Dev</span><span style='color:#f39c12'>&#40;</span><span style='color:#3498db'>Ops</span><span style='color:#e74c3c'>&#124;</span><span style='color:#3498db'>SecOps</span><span style='color:#f39c12'>&#41;</span><span style='color:#9b59b6'>&#63;</span><span style='color:#e74c3c'>&#124;</span><span style='color:#27ae60'>SRE</span><span style='color:#e74c3c'>&quot;</span> Engineer and digital nomad currently exploring the world. I write about remote work, travel, and building software from anywhere."
url: "https://devnomadic.com"
baseurl: ""

# Jekyll pagination (required for home page)
paginate: 5
paginate_path: "/blog/page:num/"

author:
  name: devnomadic
  github: devnomadic
  email: drew@devnomadic.com
  bio: "<span style='color:#e74c3c'>&quot;</span><span style='color:#3498db'>Dev</span><span style='color:#f39c12'>&#40;</span><span style='color:#3498db'>Ops</span><span style='color:#e74c3c'>&#124;</span><span style='color:#3498db'>SecOps</span><span style='color:#f39c12'>&#41;</span><span style='color:#9b59b6'>&#63;</span><span style='color:#e74c3c'>&#124;</span><span style='color:#27ae60'>SRE</span><span style='color:#e74c3c'>&quot;</span> Engineer and digital nomad currently exploring the world. I write about remote work, travel, and building software from anywhere."
  avatar: "/assets/avatar.gif"
  
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-mermaid

# Mermaid configuration
mermaid:
  src: 'https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js'

# Theme settings
dash:
  date_format: "%b %-d, %Y"
  show_author: true
  avatar_source: "local"
  avatar_path: "/assets/avatar.gif"
  show_nav: true
  nav_links:
    - url: /about/
      title: About
    - url: /archive/
      title: Archive
    - url: /tags/
      title: Tags
  social_links:
    - url: https://github.com/devnomadic
      icon: github
      color: purple
    - url: https://www.linkedin.com/in/drewkennedy
      icon: linkedin
      color: blue
    - url: mailto:drew@devnomadic.com
      icon: envelope
      color: green
      fa: true
  # disqus:
  #   shortname: devnomadic

