theme: jekyll-dash
title: devnomadic
description: "Dev&#40;Ops&#124;SecOps&#41;&#63;&#124;SRE Engineer and digital nomad currently exploring the world. I write about remote work, travel, and building software from anywhere."
url: "https://devnomadic.com"
baseurl: ""

# Jekyll pagination (required for home page)
paginate: 5
paginate_path: "/blog/page:num/"

author:
  name: devnomadic
  github: devnomadic
  email: drew@devnomadic.com
  bio: "Dev&#40;Ops&#124;SecOps&#41;&#63;&#124;SRE Engineer and digital nomad currently exploring the world. I write about remote work, travel, and building software from anywhere."
  avatar: "/assets/avatar.gif"
  
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Theme settings
dash:
  date_format: "%b %-d, %Y"
  show_author: true
  avatar_source: "local"
  avatar_path: "/assets/avatar.gif"
  show_nav: true
  nav_links:
    - url: /about/
      title: About
    - url: /archive/
      title: Archive
    - url: /tags/
      title: Tags
  social_links:
    - url: https://github.com/devnomadic
      icon: github
      color: purple
    - url: https://www.linkedin.com/in/drewkennedy
      icon: linkedin
      color: blue
    - url: mailto:drew@devnomadic.com
      icon: envelope
      color: green
      fa: true
  # disqus:
  #   shortname: devnomadic

